
spring.application.name=lyricmind
server.port=8080


spring.data.mongodb.uri=
spring.data.mongodb.database=lyricmind


spring.ai.vectorstore.mongodb.collection-name=lyricmind_vector_store
spring.ai.vectorstore.mongodb.initialize-schema=true
spring.ai.vectorstore.mongodb.path-name=embedding
spring.ai.vectorstore.mongodb.index-name=lyricmind_vector_index


spring.ai.openai.api-key=
spring.ai.openai.embedding.options.model=text-embedding-3-large
spring.ai.openai.chat.options.model=gpt-4o-mini


management.endpoints.web.exposure.include=* 